import Head from 'next/head'
import Image from 'next/image'
import flightcentral_logo  from '../public/flightcentral_logo.svg'
export default function Home() {
  return (
    <div >
      <Head>
        <title>FlightCentral</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <section className='grid'>
          <div className='pt-20 pb-10 justify-self-center'>
            <Image height={50} width={300} src={flightcentral_logo} alt="logo" />
          </div>
          <div className='justify-self-center text-3xl font-light'>
          Book Your Dream Away ......
          </div>
        </section>
        <section className='grid'>
          <div className='grid p-10 justify-self-center text-4xl font-thin'>
          <p className='justify-self-center'>We are building a great flight booking experience where you can get the best<br /> </p>
          <p className='justify-self-center'>rates for your trip to India.</p>
          </div>
          <div id="emailForm" className='justify-self-center'>
          <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeqgOfavNLG75tJ4Q_vC6FRpD23-JPISy4mhwvnw40H-_FFXA/viewform?embedded=true" width="640" height="542" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
          </div>
        </section>
      </main>

      <footer >
      </footer>
    </div>
  )
}
